name: 'Run tests'

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout repo content
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: setup python
        uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Test
        run: |
          python -m unittest find_and_lint_openapi_docs_test.py
